<?php /* Template Name: Privacy Policy Page */ ?>
<?php get_header(); ?>
<section id="breadcrumbs" class="breadcrumbs">
  <div class="container">
    <div class="d-flex justify-content-between align-items-center">
      <h4>Privacy Policy</h4>
      <ol>
        <li><a href="<?php $site_url = home_url(); echo $site_url;?>">Home</a></li>
        <li>Privacy Policy</li>
      </ol>
    </div>

  </div>
</section>
<main id="main">
  <section>
    <div class="container">
      <div class="col-md-12">
        <p>This Privacy Policy describes our policies and procedures on the collection, use, and disclosure of your
          information when you use the Service and tells you about your privacy rights and how the law protects you.</p>
        <p>We use your personal data to provide and improve the Service. By using the Service, you agree to the
          collection and use of information in accordance with this Privacy Policy.</p>
        <p><strong>Interpretation and Definitions</strong></p>
        <p><strong>Interpretation</strong></p>
        <p>The words of which the initial letter is capitalized have meanings defined under the following conditions.
          The following definitions shall have the same meaning regardless of whether they appear in singular or in
          plural.</p>
        <p><strong>Definitions</strong></p>
        <p><strong>For the purposes of this Privacy Policy:</strong></p>
        <ul>
          <li><strong>Account</strong> means a unique account created for you to access our Service or parts of our
            Service.</li>
          <li><strong>Company</strong> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement)
            refers to <?php echo get_bloginfo('name');?>.</li>
          <li><strong>Cookies</strong> are small files that are placed on your computer, mobile device, or any other
            device by a website, containing the details of your browsing history on that website among its many uses.
          </li>
          <li><strong>Country</strong> refers to Nagaland, India.</li>
          <li><strong>Device</strong> means any device that can access the Service, such as a computer, a cellphone, or
            a digital tablet.</li>
          <li><strong>Personal Data</strong> is any information that relates to an identified or identifiable
            individual.</li>
          <li><strong>Service</strong> refers to the Website.</li>
          <li><strong>Service Provider</strong> means any natural or legal person who processes the data on behalf of
            the Company. It refers to third-party companies or individuals employed by the Company to facilitate the
            Service, to provide the Service on behalf of the Company, to perform services related to the Service, or to
            assist the Company in analyzing how the Service is used.</li>
          <li><strong>Usage Data</strong> refers to data collected automatically, either generated by the use of the
            Service or from the Service infrastructure itself (for example, the duration of a page visit).</li>
          <li><strong>Website</strong> refers to <?php echo get_bloginfo('name');?>, accessible from
            <?php echo home_url();?></li>
          <li><strong>You</strong> means the individual accessing or using the Service, or the company, or other legal
            entity on behalf of which such individual is accessing or using the Service, as applicable.</li>
        </ul>

        <h4>Collecting and Using Your Personal Data</h4>
        <p><strong>Types of Data Collected</strong></p>
        <p><strong>Personal Data</strong></p>
        <p>While using our Service, we may ask you to provide us with certain personally identifiable information that
          can be used to contact or identify you. Personally identifiable information may include, but is not limited
          to:</p>
        <ul>
          <li>Email address</li>
          <li>First name and last name</li>
          <li>Phone number</li>
          <li>Usage Data</li>
        </ul>
        <p><strong>Usage Data</strong></p>
        <p>Usage Data is collected automatically when using the Service.</p>
        <p>Usage Data may include information such as your Device's Internet Protocol address (e.g. IP address), browser
          type, browser version, the pages of our Service that you visit, the time and date of your visit, the time
          spent on those pages, unique device identifiers, and other diagnostic data.</p>
        <p>When you access the Service by or through a mobile device, we may collect certain information automatically,
          including, but not limited to, the type of mobile device you use, your mobile device unique ID, the IP address
          of your mobile device, your mobile operating system, the type of mobile Internet browser you use, unique
          device identifiers, and other diagnostic data.</p>
        <p>We may also collect information that your browser sends whenever you visit our Service or when you access the
          Service by or through a mobile device.</p>

        <h4>Tracking Technologies and Cookies</h4>
        <p>We use Cookies and similar tracking technologies to track the activity on our Service and store certain
          information. Tracking technologies used are beacons, tags, and scripts to collect and track information and to
          improve and analyze our Service. The technologies we use may include:</p>
        <ul>
          <li>Cookies or Browser Cookies. A cookie is a small file placed on your Device. You can instruct your browser
            to refuse all Cookies or to indicate when a Cookie is being sent. However, if you do not accept Cookies, you
            may not be able to use some parts of our Service. Unless you have adjusted your browser setting so that it
            will refuse Cookies, our Service may use Cookies.</li>
          <li>Flash Cookies. Certain features of our Service may use local stored objects (or Flash Cookies) to collect
            and store information about your preferences or your activity on our Service. Flash Cookies are not managed
            by the same browser settings as those used for Browser Cookies. For more information on how you can delete
            Flash Cookies, please read "Where can I change the settings for disabling, or deleting local shared
            objects?" available at <a
              href="https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_"
              target="_blank">https://helpx.adobe.com/flash-player/kb/disable-local-shared-objects-flash.html#main_Where_can_I_change_the_settings_for_disabling__or_deleting_local_shared_objects_</a>
          </li>
          <li>Web Beacons. Certain sections of our Service and our emails may contain small electronic files known as
            web beacons (also referred to as clear gifs, pixel tags, and single-pixel gifs) that permit the Company, for
            example, to count users who have visited those pages or opened an email and for other related website
            statistics (for example, recording the popularity of a certain section and verifying system and server
            integrity).</li>
        </ul>
        <p>Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on your personal computer or
          mobile device when you go offline, while Session Cookies are deleted as soon as you close your web browser.
          Learn more about cookies: <a href="https://www.allaboutcookies.org/" target="_blank">What Are Cookies?</a>.
        </p>
        <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
        <ul>
          <li><strong>Necessary / Essential Cookies</strong></li>
          <p>Type: Session Cookies</p>
          <p>Administered by: Us</p>
          <p>Purpose: These Cookies are essential to provide you with services available through the Website and to
            enable you to use some of its features. They help to authenticate users and prevent fraudulent use of user
            accounts. Without these Cookies, the services that you have asked for cannot be provided, and we only use
            these Cookies to provide you with those services.</p>
          <li><strong>Cookies Policy / Notice Acceptance Cookies</strong></li>
          <p>Type: Persistent Cookies</p>
          <p>Administered by: Us</p>
          <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
          <li><strong>Functionality Cookies</strong></li>
          <p>Type: Persistent Cookies</p>
          <p>Administered by: Us</p>
          <p>Purpose: These Cookies allow us to remember choices you make when you use the Website, such as remembering
            your login details or language preference. The purpose of these Cookies is to provide you with a more
            personal experience and to avoid you having to re-enter your preferences every time you use the Website.</p>
        </ul>
        <p>For more information about the cookies we use and your choices regarding cookies, please visit our <a
            href="https://nagaland.gov.in/cookies-policy" target="_blank">Cookies Policy</a> or the Cookies section of
          our Privacy Policy.</p>

        <h4>Use of Your Personal Data</h4>
        <p>The Company may use Personal Data for the following purposes:</p>
        <ul>
          <li>To provide and maintain our Service, including to monitor the usage of our Service.</li>
          <li>To manage your Account: to manage your registration as a user of the Service. The Personal Data you
            provide can give you access to different functionalities of the Service that are available to you as a
            registered user.</li>
          <li>For the performance of a contract: the development, compliance, and undertaking of the purchase contract
            for the products, items, or services you have purchased or of any other contract with us through the
            Service.</li>
          <li>To contact you: To contact you by email, telephone calls, SMS, or other equivalent forms of electronic
            communication, such as a mobile application's push notifications regarding updates or informative
            communications related to the functionalities, products, or contracted services, including the security
            updates, when necessary or reasonable for their implementation.</li>
          <li>To provide you with news, special offers, and general information about other goods, services, and events
            which we offer that are similar to those that you have already purchased or enquired about unless you have
            opted not to receive such information.</li>
          <li>To manage your requests: To attend and manage your requests to us.</li>
          <li>For other purposes: We may use your information for other purposes, such as data analysis, identifying
            usage trends, determining the effectiveness of our promotional campaigns, and to evaluate and improve our
            Service, products, services, marketing, and your experience.</li>
        </ul>

        <h4>Disclosure of Your Personal Data</h4>
        <p>We may share your personal information in the following situations:</p>
        <ul>
          <li><strong>With Service Providers:</strong> We may share your personal information with Service Providers to
            monitor and analyze the use of our Service, to contact you.</li>
          <li><strong>With Affiliates:</strong> We may share your information with our affiliates, in which case we will
            require those affiliates to honor this Privacy Policy. Affiliates include our parent company and any other
            subsidiaries, joint venture partners, or other companies that we control or that are under common control
            with us.</li>
          <li><strong>With Business Partners:</strong> We may share your information with our business partners to offer
            you certain products, services, or promotions.</li>
          <li><strong>With Other Users:</strong> When you share personal information or otherwise interact in the public
            areas with other users, such information may be viewed by all users and may be publicly distributed outside.
          </li>
          <li><strong>With Your Consent:</strong> We may disclose your personal information for any other purpose with
            your consent.</li>
        </ul>

        <h4>Retention of Your Personal Data</h4>
        <p>The Company will retain your Personal Data only for as long as is necessary for the purposes set out in this
          Privacy Policy. We will retain and use your Personal Data to the extent necessary to comply with our legal
          obligations (for example, if we are required to retain your data to comply with applicable laws), resolve
          disputes, and enforce our legal agreements and policies.</p>
        <p>The Company will also retain Usage Data for internal analysis purposes. Usage Data is generally retained for
          a shorter period of time, except when this data is used to strengthen the security or to improve the
          functionality of our Service, or we are legally obligated to retain this data for longer time periods.</p>

        <h4>Transfer of Your Personal Data</h4>
        <p>Your information, including Personal Data, is processed at the Company's operating offices and in any other
          places where the parties involved in the processing are located. It means that this information may be
          transferred to — and maintained on — computers located outside of your state, province, country, or other
          governmental jurisdiction where the data protection laws may differ than those from your jurisdiction.</p>
        <p>Your consent to this Privacy Policy followed by your submission of such information represents your agreement
          to that transfer.</p>
        <p>The Company will take all steps reasonably necessary to ensure that your data is treated securely and in
          accordance with this Privacy Policy, and no transfer of your Personal Data will take place to an organization
          or a country unless there are adequate controls in place including the security of your data and other
          personal information.</p>

        <h4>Disclosure of Your Personal Data</h4>
        <p><strong>Business Transactions</strong></p>
        <p>If the Company is involved in a merger, acquisition, or asset sale, your Personal Data may be transferred. We
          will provide notice before your Personal Data is transferred and becomes subject to a different Privacy
          Policy.</p>
        <p><strong>Law enforcement</strong></p>
        <p>Under certain circumstances, the Company may be required to disclose your Personal Data if required to do so
          by law or in response to valid requests by public authorities (e.g. a court or a government agency).</p>
        <p><strong>Other legal requirements</strong></p>
        <p>The Company may disclose your Personal Data in the good faith belief that such action is necessary to:</p>
        <ul>
          <li>Comply with a legal obligation</li>
          <li>Protect and defend the rights or property of the Company</li>
          <li>Prevent or investigate possible wrongdoing in connection with the Service</li>
          <li>Protect the personal safety of users of the Service or the public</li>
          <li>Protect against legal liability</li>
        </ul>

        <h4>Security of Your Personal Data</h4>
        <p>The security of your Personal Data is important to us, but remember that no method of transmission over the
          Internet, or method of electronic storage is 100% secure. While we strive to use commercially acceptable means
          to protect your Personal Data, we cannot guarantee its absolute security.</p>

        <h4>Children's Privacy</h4>
        <p>Our Service does not address anyone under the age of 13. We do not knowingly collect personally identifiable
          information from anyone under the age of 13. If you are a parent or guardian and you are aware that your child
          has provided us with Personal Data, please contact us. If we become aware that we have collected Personal Data
          from anyone under the age of 13 without verification of parental consent, we take steps to remove that
          information from our servers.</p>
        <p>If we need to rely on consent as a legal basis for processing your information and your country requires
          consent from a parent, we may require your parent's consent before we collect and use that information.</p>

        <h4>Links to Other Websites</h4>
        <p>Our Service may contain links to other websites that are not operated by us. If you click on a third party
          link, you will be directed to that third party's site. We strongly advise you to review the Privacy Policy of
          every site you visit.</p>
        <p>We have no control over and assume no responsibility for the content, privacy policies, or practices of any
          third party sites or services.</p>

        <h4>Changes to this Privacy Policy</h4>
        <p>We may update our Privacy Policy from time to time. We will notify you of any changes by posting the new
          Privacy Policy on this page.</p>
        <p>We will let you know via email and/or a prominent notice on our Service, prior to the change becoming
          effective and update the "Last updated" date at the top of this Privacy Policy.</p>
        <p>You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy
          are effective when they are posted on this page.</p>

        <h4>Contact Us</h4>
        <p>If you have any questions about this Privacy Policy, you can contact us:</p>
        <p>
          <?php
            if (is_active_sidebar('address_widget')) {
              dynamic_sidebar('address_widget');
            }
          ?>
        </p>
      </div>
    </div>
  </section>

</main><!-- End #main -->
<?php get_footer(); ?>